# Generated by Django 5.2.1 on 2025-06-03 17:29

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=main_app.models.get_today),
        ),
    ]
